INSERT INTO DistrictMaster VALUES('Alipurduar', '25');
INSERT INTO DistrictMaster VALUES('Bankura', '25');
INSERT INTO DistrictMaster VALUES('Birbhum', '25');
INSERT INTO DistrictMaster VALUES('Cooch Behar', '25');
INSERT INTO DistrictMaster VALUES('Dakshin Dinajpur', '25');	
INSERT INTO DistrictMaster VALUES('Darjeeling', '25');
INSERT INTO DistrictMaster VALUES('Hooghly', '25');	
INSERT INTO DistrictMaster VALUES('Howrah', '25');
INSERT INTO DistrictMaster VALUES('Jalpaiguri', '25');
INSERT INTO DistrictMaster VALUES('Jhargram', '25');	
INSERT INTO DistrictMaster VALUES('Kalimpong', '25');	
INSERT INTO DistrictMaster VALUES('Kolkata', '25');	
INSERT INTO DistrictMaster VALUES('Malda', '25');
INSERT INTO DistrictMaster VALUES('Murshidabad', '25');	
INSERT INTO DistrictMaster VALUES('Nadia', '25');	
INSERT INTO DistrictMaster VALUES('North 24 Parganas', '25');	
INSERT INTO DistrictMaster VALUES('Paschim Bardhaman', '25');	
INSERT INTO DistrictMaster VALUES('Paschim Medinipur', '25');	
INSERT INTO DistrictMaster VALUES('Purba Bardhaman', '25');	
INSERT INTO DistrictMaster VALUES('Purba Medinipur', '25');	
INSERT INTO DistrictMaster VALUES('Purulia', '25');	
INSERT INTO DistrictMaster VALUES('South 24 Parganas', '25');	
INSERT INTO DistrictMaster VALUES('Uttar Dinajpur', '25');